### ISSUE TITLE
Sporadic problem uploading to 51515 hub (fix included)

### ISSUE THREAD

**Issue by martya0** [sanjayseshan/spikeprime-tools#11]
Using the Mindstorms 51515 hub, I sometimes get the following when trying to upload:

Traceback (most recent call last):
  File "/home/marty/spiketools/spikejsonrpc.py", line 226, in <module>
    args.func()
  File "/home/marty/spiketools/spikejsonrpc.py", line 154, in handle_upload
    start = rpc.start_write_program(name, size, args.to_slot, now, now)
  File "/home/marty/spiketools/spikejsonrpc.py", line 80, in start_write_program
    return self.send_message('start_write_program', {'slotid':slot, 'size': size, 'meta': meta})
  File "/home/marty/spiketools/spikejsonrpc.py", line 55, in send_message
    return self.recv_response(id)
  File "/home/marty/spiketools/spikejsonrpc.py", line 60, in recv_response
    if 'i' in m and m['i'] == id:
TypeError: argument of type 'NoneType' is not iterable

I believe I have fixed this by adding the following lines on line 60:
      if type(m) is type(None) :
        continue

Now if the hub is taking too long to re-establish its ready state, your code will wait for it and it will succeed.

Thanks for the great tool!

**Comment by dmusican** [comment]
Thanks so much for this fix; it's exactly what I needed on a Spike Prime when I was having the same problem when connecting via bluetooth.

**Comment by dmusican** [comment]
I'll partially take it back. This fix makes the error message go away, but when using it over bluetooth on my Spike Prime, the brick starts behaving unreliably. Sometimes the brick beeps somewhat sporadically, and the upload seems to work (I see a bluetooth logo on the light matrix), but the program won't actually run.
