### ISSUE TITLE
Error starting program

### ISSUE THREAD

**Issue by ingoha** [sanjayseshan/spikeprime-tools#7]
When I try to start a program uploaded before, I encounter this error:
`DEBUG:root:Cannot parse JSON: bytearray(b' []], [0, []], [0, []], [75, [0, 0, -27, 0]], [0, []], [0, []], [8, 998, 99], [0, 9, -3], [29, 0, -84], "", 0]}')
`

**Comment by ingoha** [comment]
Complete output:
```
DEBUG:root:sending: {"m": "program_execute", "p": {"slotid": 0}, "i": "iLBO"}
DEBUG:root:Cannot parse JSON: bytearray(b' []], [0, []], [0, []], [75, [0, 0, -27, 0]], [0, []], [0, []], [8, 998, 99], [0, 9, -3], [29, 0, -84], "", 0]}')
DEBUG:root:while waiting for response: {'m': 0, 'p': [[0, []], [0, []], [0, []], [75, [0, 0, -27, 0]], [0, []], [0, []], [7, 999, 98], [1, 9, -3], [29, 0, -84], '', 0]}
DEBUG:root:while waiting for response: {'m': 12, 'p': [None, False]}
DEBUG:root:response: {'i': 'iLBO', 'r': None}
```

**Comment by ingoha** [comment]
Using this tool, is works: https://github.com/ws1088/spike-tools-ng
Output is:
```
Error: Traceback (most recent call last):
  File "programrunner/__init__.py", line 1, in start_program
  File "./projects/420.py", line 34
IndentationError: unindent doesn't match any outer indent level
```

**Comment by ingoha** [comment]
Perhaps we should build a "best of breeds" version by amalgating spike-tools, spike-tools-ng and this project?

**Comment by sanjayseshan** [comment]
Hmmm. I thought this worked. Albeit, I last checked a couple months ago.

```
> Error: Traceback (most recent call last):
>   File "programrunner/__init__.py", line 1, in start_program
>   File "./projects/420.py", line 34
> IndentationError: unindent doesn't match any outer indent level
```
This seems a little strange since the file organization on the newest firmware has changed. It should be `./projects/420/__init__.py`. What firmware version are you using?

**Comment by sanjayseshan** [comment]
> Perhaps we should build a "best of breeds" version by amalgating spike-tools, spike-tools-ng and this project?

Seems like a good idea. Both projects have the same base code from https://github.com/nutki/spike-tools so it might be easy to merge the appropriate lines.

**Comment by ingoha** [comment]
I used Firmware version: 1.0.6.34; Runtime version: 2.1.4.13

> Hmmm. I thought this worked. Albeit, I last checked a couple months ago.
> 
> ```
> > Error: Traceback (most recent call last):
> >   File "programrunner/__init__.py", line 1, in start_program
> >   File "./projects/420.py", line 34
> > IndentationError: unindent doesn't match any outer indent level
> ```
> 
> This seems a little strange since the file organization on the newest firmware has changed. It should be `./projects/420/__init__.py`. What firmware version are you using?

Firmware version: 1.0.6.34; Runtime version: 2.1.4.13
