### ISSUE TITLE
Not all files have a 'size' on my Spikehub

### ISSUE THREAD

**Issue by BertLindeman** [sanjayseshan/spikeprime-tools#9]
On my Spike hub at the current firmware level, I get this error on "ls" command:
```Traceback (most recent call last):
  File "./spikejsonrpcapispike.py", line 219, in <module>
    args.func()
  File "./spikejsonrpcapispike.py", line 135, in handle_list
    print("%4s %-40s %5db %-20s %-12s %-10s" % (i, decoded_name, sl['size'], modified, project, type))
KeyError: 'size'
```

Will create a PR

**Comment by sanjayseshan** [comment]
Just merged. Unfortunately when LEGO updates the firmware, sometimes some features break and need to be updated.
